#!/usr/bin/env bash
set -euo pipefail

SNAP_BASE="${SNAP_BASE:-/opt/somleng/snapshots}"

ts_now() { date +%Y%m%d-%H%M%S; }

require() { command -v "$1" >/dev/null 2>&1 || { echo "[-] missing: $1" >&2; return 1; }; }
have()    { command -v "$1" >/dev/null 2>&1; }

mk_snap_dir() {
  local mod="${1:-unknown}"
  local ts; ts="$(ts_now)"
  SNAP_DIR="${SNAP_BASE}/${ts}"
  mkdir -p "${SNAP_DIR}"/{meta,docker,network,somleng,fs,core_dumps,logs}
  {
    echo "# Snapshot ${ts}"
    echo ""
    echo "- module: \`${mod}\`"
    echo "- host: \`$(hostname -f 2>/dev/null || hostname)\`"
    echo "- date(ISO): \`$(date -Is)\`"
    echo "- kernel: \`$(uname -srmo)\`"
    echo ""
    echo "## Contents"
  } > "${SNAP_DIR}/index.md"
  echo "${SNAP_DIR}"
}

append_index_link() {
  # usage: append_index_link <path> [label]
  local path="$1"; local label="${2:-$1}"
  printf -- "- [%s](%s)\n" "$label" "$path" >> "${SNAP_DIR}/index.md"
}

save_cmd() {
  local rel="$1"; shift
  local out="${SNAP_DIR}/${rel}"
  mkdir -p "$(dirname "$out")"
  {
    echo "\$ $*"
    set +e
    "$@" 2>&1
    local rc=$?
    set -e
    echo "[exit=$rc]"
  } | tee "$out" >/dev/null
  append_index_link "${rel}" "${rel}"
}

save_file_copy() {
  local src="$1" dst="${SNAP_DIR}/${2}"
  mkdir -p "$(dirname "$dst")"
  if [ -r "$src" ]; then
    cat "$src" > "$dst"
  else
    echo "unreadable: $src" > "$dst"
  fi
  append_index_link "$2" "$2"
}

gen_manifest_sha256() {
  ( cd "${SNAP_DIR}" && find . -maxdepth 6 -type f -print0 | sort -z | xargs -0 sha256sum ) > "${SNAP_DIR}/manifest.sha256" || true
  append_index_link "manifest.sha256" "manifest.sha256"
}

finish_note() {
  {
    echo ""
    echo "> Generated by somleng-snapctl $(date -Is)"
  } >> "${SNAP_DIR}/index.md"
}
